Add logging for events
nabokihms/events_exporter pull request #1
Opened 2022-07-13 11:51 UTC by alex123012

In many cases, event messages are one of the main parts of debugging. So I'm proposing a new flag that logs the events received by the informer to stdout.

2022-07-13 12:26 UTC, alex123012 commented on main.go
> +	logFormat := fmt.Sprintf("logger:stdout?json=%t", logEvents)
Some info for this line - I'm assuming if we don't use event logging so we don't need json output, and vice versa

2022-07-20 11:20 UTC, nabokihms requested changes
@alex123012, thank you for submitting the PR! It will be a great addition to the project.

1. I left a couple of suggestions. Please look through them when you have time.
2. Helm chart doc should be updated. Could you please run `make docs` to automatically generate the doc?
3. Let's also add a new flag to the README.md.

2022-07-20 11:20 UTC, nabokihms commented on charts/events_exporter/values.yaml
> +  # -- Log all events resources to stdout (helps with debugging kube api)
```suggestion
  # -- Log all events resources to stdout (helps with debugging Kubernetes API)
```

2022-07-20 11:20 UTC, nabokihms commented on pkg/kube/event.go
>  		event := obj.(*v1.Event)
This is the right place to put your logging logic.

2022-07-20 11:20 UTC, nabokihms commented on pkg/kube/event.go
> +		data, _ := json.Marshal(event)
I did not get Marshal/Unmarshal here. You need to log an event before converting it to `*v1.Event`.

```go
return func(obj interface{}) {
    log.With("event", obj).Infoln("received event")
    event := obj.(*v1.Event)
}
```
With this exporter will avoid additional marshalling.

2022-07-20 11:20 UTC, nabokihms commented on pkg/kube/event.go
> +	if logEvents {
Let's move it out of this function. The purpose of the `EventToSample` function is convertion only, not logging.

2022-07-20 11:20 UTC, nabokihms commented on main.go
> +	logFormat := fmt.Sprintf("logger:stdout?json=%t", logEvents)
I do not see a problem there. Let's make all logs JSON-formatted by default.

2022-07-20 11:20 UTC, nabokihms commented on charts/events_exporter/values.yaml
> +  logEvents: true
Also, if it is only for debugging, maybe instead of adding a trigger, the exporter can print all received events if the log level equals `debug`? What do you think?

2022-08-10 18:11 UTC, alex123012 commented on charts/events_exporter/values.yaml
> +  logEvents: true
I think, this is a good idea:)

2022-08-10 18:45 UTC, alex123012 commented
@nabokihms Hi!
I've looked and fixed all your suggestions and move event log only for "debug" log-level

2022-08-10 18:46 UTC, alex123012 commented
Also, I've hardcode json-formatted log style

2022-08-11 13:04 UTC, nabokihms commented
There are a couple of things to do to release a new chart, but I think I can do it myself. Besides it, LGTM!

2022-08-11 13:04 UTC, merged